#! /bin/sh
killall redshift
killall polybar

sh ~/.config/polybar/launch.sh
# setxkbmap fr
setxkbmap -option grp:alt_shift_toggle fr,us &

pgrep -x sxhkd >/dev/null || sxhkd &
picom &
dunst &

xrdb ~/.Xresources
#wal -R
redshift -x
redshift -l 46.160328:-1.151139 &

bspc monitor -d I II III IV V VI VII VIII IX X
#
#if [[ $(xrandr -q | grep "DP-0 connected") ]]; then
#    xrandr --output DP-0 --rate 144 --mode 2560x1440 --auto --output DP-4 --rate 144 --mode 2560x1440 --left-of DP-0
#    bspc monitor DP-0 -d II III IV V VI VII VIII IX X
#fi

#. "${HOME}/.cache/wal/colors.sh"

bspc config pointer_motion_interval 7ms
bspc config normal_border_color "#444444"
# bspc config focused_border_color "#00FF00"
bspc config focused_border_color "#00FF00"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# Set the border colors.
# bspc config normal_border_color "$color2"
bspc config active_border_color "#330000"
# bspc config focused_border_color "$color1"
# Use the line below if you are on bspwm >= 0.9.4
# bspc config presel_feedback_color "$color3"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config top_padding 0
bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc config pointer_action2 resise_size
# bspc config pointer_action2 resize_corner

bspc config pointer_motion_interval 7ms

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

dunstify -u low -t 1000 "Bspwm" "Bspwm is ready"
